# Generated by Django 5.1.1 on 2024-11-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_auto_20241111_1346'),
    ]

    operations = [
    ]
