# Generated by Django 5.1.2 on 2024-10-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('id_livros', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
