# Generated by Django 5.1.1 on 2024-11-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencialivro', '0002_alter_livros_ano'),
        ('gerencialivro', '0002_livro_quantidade'),
    ]

    operations = [
    ]
