# Generated by Django 5.1.1 on 2024-11-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
    ]

    operations = [
    ]
