# Generated by Django 5.1.1 on 2024-11-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_cliente_senha'),
        ('emprestimo', '0003_auto_20241111_1359'),
    ]

    operations = [
    ]
